import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {verifyGoogleToken} from '../server/auth.js';
import worker from '../dist/server/index.js';
const clientId='test-client.apps.googleusercontent.com';
const keys=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
const jwk={...await crypto.subtle.exportKey('jwk',keys.publicKey),kid:'test-key',alg:'RS256',use:'sig'};
const encode=v=>Buffer.from(typeof v==='string'?v:JSON.stringify(v)).toString('base64url');
async function jwt(nonce,overrides={},header={}){const now=Math.floor(Date.now()/1000);const unsigned=encode({alg:'RS256',kid:'test-key',...header})+'.'+encode({iss:'https://accounts.google.com',aud:clientId,sub:'google-subject',name:'Tester',iat:now,exp:now+3600,nonce,...overrides});return unsigned+'.'+Buffer.from(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',keys.privateKey,new TextEncoder().encode(unsigned))).toString('base64url');}
test('Google verifier rejects wrong audience, issuer, nonce, expiry, algorithm and forged signature',async()=>{const options={resolveKey:async()=>jwk};const token=await jwt('nonce');assert.equal((await verifyGoogleToken(token,clientId,'nonce',options)).sub,'google-subject');for(const override of [{aud:'attacker'},{iss:'https://attacker.test'},{nonce:'other'},{exp:1},{iat:Math.floor(Date.now()/1000)+3600},{sub:''}])await assert.rejects(verifyGoogleToken(await jwt('nonce',override),clientId,'nonce',options));await assert.rejects(verifyGoogleToken(await jwt('nonce',{}, {alg:'none'}),clientId,'nonce',options));const parts=token.split('.');parts[1]=encode({aud:clientId,sub:'forged'});await assert.rejects(verifyGoogleToken(parts.join('.'),clientId,'nonce',options));});
function env(configured=true){const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));return {sql,...(configured?{GOOGLE_CLIENT_ID:clientId}:{}),DB:{withSession(){return this;},prepare(text){let args=[];return {bind(...v){args=v;return this;},async first(){return sql.prepare(text).get(...args);},async all(){return {results:sql.prepare(text).all(...args)};},async run(){return {meta:{changes:Number(sql.prepare(text).run(...args).changes)}};}}}}};}
async function call(e,path,body,cookie='',origin='https://game.test'){return worker.fetch(new Request('https://game.test/api/auth/'+path,{method:body?'POST':'GET',headers:{cookie,...(body?{'content-type':'application/json',origin}:{})},...(body?{body:JSON.stringify(body)}:{})}),e);}
const cookies=r=>r.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');
test('guest config is honest and sign-in refuses cross-origin requests',async()=>{const e=env(false);assert.deepEqual(await (await call(e,'me')).json(),{googleEnabled:false,clientId:'',user:null,csrf:null});assert.equal((await call(e,'challenge',{})).status,503);assert.equal((await call(e,'challenge',{},'','https://attacker.test')).status,403);e.sql.close();});
test('Google challenge binds to browser, cannot replay, and logout revokes session',async()=>{const e=env(),oldFetch=globalThis.fetch;globalThis.fetch=async url=>{assert.equal(url,'https://www.googleapis.com/oauth2/v3/certs');return Response.json({keys:[jwk]},{headers:{'cache-control':'max-age=3600'}});};try{const cr=await call(e,'challenge',{}),challenge=await cr.json(),challengeCookie=cookies(cr);assert.match(cr.headers.get('set-cookie'),/Secure; HttpOnly; SameSite=Lax/);const payload={credential:await jwt(challenge.nonce),csrf:challenge.csrf};assert.equal((await call(e,'google',payload)).status,401);assert.equal((await call(e,'google',{...payload,csrf:'wrong'},challengeCookie)).status,401);const login=await call(e,'google',payload,challengeCookie);assert.equal(login.status,200);const account=await login.json(),session=cookies(login);assert.equal(account.user.name,'Tester');assert.equal((await call(e,'google',payload,challengeCookie)).status,401);assert.equal((await (await call(e,'me',undefined,session)).json()).user.name,'Tester');assert.equal((await call(e,'logout',{csrf:'wrong'},session)).status,401);assert.equal((await call(e,'logout',{csrf:account.csrf},session)).status,200);assert.equal((await (await call(e,'me',undefined,session)).json()).user,null);assert.equal(e.sql.prepare('SELECT COUNT(*) AS count FROM auth_sessions').get().count,0);}finally{globalThis.fetch=oldFetch;e.sql.close();}});
test('account deletion removes profile and every session',async()=>{const e=env();e.sql.prepare('INSERT INTO auth_profiles VALUES (?,?,?,?)').run('u','sub','Tester',Date.now());const secret='a'.repeat(64),{hash}=await import('../server/auth.js');for(const token of [secret,'b'.repeat(64)])e.sql.prepare('INSERT INTO auth_sessions VALUES (?,?,?,?)').run(await hash(token),'u','csrf',Date.now()+100000);assert.equal((await call(e,'delete',{csrf:'csrf'},'__Host-lexivanto_session='+secret)).status,200);assert.equal(e.sql.prepare('SELECT COUNT(*) AS count FROM auth_profiles').get().count,0);assert.equal(e.sql.prepare('SELECT COUNT(*) AS count FROM auth_sessions').get().count,0);e.sql.close();});
