import {test} from 'node:test';import assert from 'node:assert/strict';
import {makeRoom,begin,guess,expire,view,ready,rematch} from '../public/game.js';
const words=new Set(['apple','ample','angle','crane','slate','gamer','audio','arise','tears','house','flame','bread','stone','pride']);
function game(config={}){const g=makeRoom({mode:'duel',seconds:30,...config},'A','a','apple',100);g.players[1]={name:'B',auth:'b',ready:true};begin(g,100);return g;}
const submit=(g,p,w,t)=>guess(g,p,w,words,t);
test('duel hides opponent submission until both lock, then advances',()=>{const g=game();submit(g,0,'crane',200);assert.equal(g.rows.length,0);assert.equal(view(g,1).ownPending,'');assert(!JSON.stringify(view(g,1)).includes('crane'));assert.equal(view(g,0).answer,null);submit(g,1,'slate',300);assert.equal(g.rows.length,2);assert.equal(g.round,2);assert.equal(g.deadline,0);});
test('simultaneous correct guesses use submission time; exact ties draw',()=>{for(const time of [200,201]){const g=game();submit(g,0,'apple',200);assert.equal(g.status,'playing');submit(g,1,'apple',time);assert.equal(g.winner,time===200?null:0);}});
test('sudden death starts only after six completed rounds',()=>{const g=game();const tries=['crane','slate','gamer','audio','arise','tears','house','flame','bread','stone','pride','angle'];for(let i=0;i<6;i++){submit(g,0,tries[2*i],1000+i*100);submit(g,1,tries[2*i+1],1050+i*100);}assert.equal(g.round,7);assert.equal(g.status,'playing');assert.equal(g.deadline,31550);expire(g,31550);assert.equal(g.status,'finished');assert.equal(g.winner,null);});
test('invalid guesses preserve clock, expiry rejects answer and awards submitted opponent',()=>{const g=game({sudden:false});assert.throws(()=>submit(g,0,'zzzzz',200));assert.equal(g.deadline,30100);submit(g,1,'crane',250);submit(g,0,'apple',30100);assert.equal(g.winner,1);assert.equal(g.reason,'timeout');});
test('race hides opponent board and rewards fewer guesses',()=>{const g=game({mode:'race',seconds:300});submit(g,0,'crane',200);submit(g,0,'apple',300);assert.equal(g.status,'playing');assert.equal(view(g,1).boards[0].length,0);submit(g,1,'apple',400);assert.equal(g.winner,1);assert.equal(view(g,1).boards[0].length,2);});
test('race equal count rewards earlier solve; unsolved player loses after exhausting winning count',()=>{const g=game({mode:'race',seconds:300});submit(g,0,'apple',200);submit(g,1,'crane',300);assert.equal(g.winner,0);});
test('coop alternates, shares win, and respects attempt limit',()=>{const g=game({mode:'coop',seconds:0});assert.throws(()=>submit(g,1,'crane',200));submit(g,0,'crane',200);submit(g,1,'apple',300);assert.equal(g.winner,'team');const h=game({mode:'coop',seconds:0,attempts:6});['crane','slate','gamer','audio','arise','tears'].forEach((w,i)=>submit(h,i%2,w,200+i));assert.equal(h.reason,'attempts');});
test('rematch requires both ready and changes secret',()=>{const g=game();submit(g,0,'apple',200);submit(g,1,'crane',300);rematch(g,0,'angle');assert.equal(g.status,'waiting');assert.equal(g.players[1].ready,false);ready(g,1,500);assert.equal(g.answer,'angle');assert.equal(g.match,2);assert.equal(g.rows.length,0);});
test('response Duel starts its clock only on first valid lock, hides word, and resets next round',()=>{const g=game({clockMode:'response',sudden:false});assert.equal(g.deadline,0);assert.throws(()=>submit(g,0,'zzzzz',90000));assert.equal(g.deadline,0);submit(g,0,'crane',100000);assert.equal(g.deadline,130000);const opponent=view(g,1,100001);assert.equal(opponent.submitted[0],true);assert.equal(opponent.deadline,130000);assert.equal(opponent.ownPending,'');assert.equal(opponent.rows.length,0);assert(!JSON.stringify(opponent).includes('crane'));assert.throws(()=>submit(g,0,'audio',101000));assert.equal(g.deadline,130000);submit(g,1,'slate',129999);assert.equal(g.round,2);assert.equal(g.deadline,0);assert.throws(()=>submit(g,1,'crane',140000));assert.equal(g.deadline,0);});
test('response deadline cannot be extended by invalid guesses and exact-deadline replies lose',()=>{const g=game({clockMode:'response',seconds:30});submit(g,1,'crane',1000);assert.throws(()=>submit(g,0,'zzzzz',10000));assert.equal(g.deadline,31000);submit(g,0,'apple',31000);assert.equal(g.winner,1);assert.equal(g.reason,'timeout');});
test('untimed response Duel stays untimed after either lock and rematch resets timer',()=>{const g=game({clockMode:'response',seconds:0});submit(g,1,'crane',50000);assert.equal(g.deadline,0);submit(g,0,'apple',100000);rematch(g,0,'angle');ready(g,1,200000);assert.equal(g.deadline,0);assert.deepEqual(g.pending,[null,null]);});
