import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import * as game from '../public/game.js';import {normalize,botDelay} from '../public/engine.js';
class Element{constructor(id=''){this.id=id;this.children=[];this.value='';this.textContent='';this.style={setProperty(){}};this.classList={toggle(){},remove(){}};this.dataset={};this.tagName='DIV';this.scrollHeight=0;}setAttribute(key,value){this[key]=value;}replaceChildren(...children){this.children=children;}append(c){this.children.push(c);}addEventListener(){}focus(){}select(){}showModal(){this.open=true;}close(){this.open=false;}}
async function harness(){const nodes=new Map;const get=id=>{if(!nodes.has(id))nodes.set(id,new Element(id));return nodes.get(id);};get('difficulty').value='easy';get('nickname').value='Tester';get('sudden').value='yes';get('attempts').value='6';const storage=new Map;const ctx={...game,normalize,botDelay,setupAccount:()=>()=>{},setupSocial:()=>({accountChanged(){},refresh(){}}),console,Set,Math,Date,crypto,AbortSignal,URLSearchParams,location:{pathname:'/',origin:'https://game.test',search:''},history:{replaceState(){}},navigator:{},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},sessionStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},document:{getElementById:get,querySelectorAll:()=>[],createElement:()=>new Element,body:{classList:{toggle(){},remove(){}}},documentElement:{dataset:{}},addEventListener(){}},setInterval(){},fetch:async path=>({ok:true,json:async()=>JSON.parse(fs.readFileSync(new URL('../public/'+path,import.meta.url),'utf8'))})};vm.createContext(ctx);vm.runInContext(fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8').replace(/^import[^\n]+\n/gm,''),ctx);await new Promise(setImmediate);return {ctx,get,run:s=>vm.runInContext(s,ctx)};}
test('touch-only co-op starts with enabled keys and accepts on-screen guess',async()=>{const h=await harness();h.run("mode='coop';setup()");await h.run('create()');assert.equal(h.run('canType()'),true);const keys=h.get('keyboard').children.flatMap(row=>row.children);assert(keys.length>20);assert(keys.every(k=>!k.disabled));h.run("key('c');key('r');key('a');key('n');key('e')");assert.equal(h.run('draft'),'crane');await h.run('submit()');assert.equal(h.run('local.rows.length'),1);assert.equal(h.run('draft'),'');});
test('unchanged render preserves keyboard nodes, busy menu cannot abandon action',async()=>{const h=await harness();await h.run('create()');const first=h.get('keyboard').children[0];h.run('render()');assert.equal(h.get('keyboard').children[0],first);h.run("busy=true;menu()");assert(h.run('state'));h.run('busy=false;menu()');assert.equal(h.run('state'),null);});

test('custom clock, difficulty and nickname persist and switching modes restores each clock',async()=>{const h=await harness();h.get('clock').value='60';h.get('difficulty').value='normal';h.run('remember()');h.run("mode='race';setup()");h.get('clock').value='600';h.run('remember()');h.run("mode='duel';setup()");assert.equal(Number(h.get('clock').value),60);assert.equal(h.get('difficulty').value,'normal');h.run("mode='race';setup()");assert.equal(Number(h.get('clock').value),600);assert.equal(h.run('preferences.name'),'Tester');});

test('menu starts with mode choice, preserves name on Back and bots ignore friend clocks',async()=>{const h=await harness();assert.equal(h.run('step'),'modes');h.run("chooseMode('race')");assert.equal(h.run('step'),'opponent');h.run("chooseOpponent('bot')");assert.equal(h.run('step'),'bot');h.run('back()');assert.equal(h.run('step'),'opponent');assert.equal(h.get('nickname').value,'Tester');h.run("chooseOpponent('bot')");h.get('clock').value='600';await h.run('create()');assert.equal(h.run('local.settings.seconds'),0);assert.equal(h.run('local.deadline'),0);});
test('nickname is validated before search and signed profile supplies the next match name',async()=>{const h=await harness();h.get('nickname').value=' ';h.run("chooseMode('duel');chooseOpponent('online')");assert.equal(h.run('search'),null);assert(h.get('menu-error').textContent);h.run("signedAccount={name:'Google Player'}");await h.run('create()');assert.equal(h.run('local.players[0].name'),'Google Player');});
test('cancelled search ignores a late matched response',async()=>{const h=await harness();let finish;h.ctx.fetch=async(path)=>path.endsWith('/cancel')?{ok:true,json:async()=>({status:'cancelled'})}:new Promise(resolve=>finish=resolve);h.run("chooseMode('duel');chooseOpponent('online')");assert.equal(h.run('step'),'search');await h.run('cancelSearch()');assert.equal(h.run('step'),'opponent');finish({ok:true,json:async()=>({status:'matched',room:{}})});await new Promise(setImmediate);assert.equal(h.run('state'),null);assert.equal(h.run('search'),null);});
test('invite screen keeps nickname and join visible, Back restores normal choices',async()=>{const h=await harness();h.run("showStep('invite')");assert.equal(h.get('step-opponent').hidden,false);assert.equal(h.get('step-friend').hidden,false);assert.equal(h.get('opponent-options').hidden,true);h.run('back()');assert.equal(h.run('step'),'modes');h.run("chooseMode('coop')");assert.equal(h.get('opponent-options').hidden,false);assert.equal(h.get('friend-create').hidden,false);});
test('locked opponent is explicit and draft row stays separate from revealed history',async()=>{const h=await harness();await h.run('create()');h.run("key('c');key('r')");assert.equal(h.get('draft-row').children.length,1);assert.equal(h.get('draft-row').children[0].children[0].textContent,'C');assert.equal(h.get('board').children.length,2);h.run("guess(local,1,'audio',dictionaries.en.set,Date.now());state=view(local,0);render()");assert.match(h.get('other-status').textContent,/locked/i);assert.match(h.get('turn-label').textContent,/locked/i);});
test('theme preference survives menu changes and online timing stays fixed despite an old saved preference',async()=>{const h=await harness();h.run("applyTheme('dark');chooseMode('duel')");assert.equal(h.ctx.document.documentElement.dataset.theme,'dark');let payload;h.ctx.fetch=async(path,opts)=>{payload=JSON.parse(opts.body);return {ok:true,json:async()=>({status:'searching'})};};h.run("onlinePreferences.duel=60;chooseOpponent('online')");await new Promise(setImmediate);assert.equal(payload.seconds,30);assert.equal(h.run('onlineRules().clockMode'),'response');});
test('navigation labels name the destination and practice has a clear exit',async()=>{const h=await harness();h.run("chooseMode('duel')");assert.equal(h.get('back-button').textContent,'← Game modes');assert.equal(h.get('menu-button').hidden,true);h.run("chooseOpponent('bot')");assert.equal(h.get('back-button').textContent,'← Change opponent');await h.run('create()');assert.equal(h.get('back-button').hidden,true);assert.equal(h.get('menu-button').textContent,'End practice');h.run('requestMenu()');assert.equal(h.get('leave-title').textContent,'End practice?');assert(h.get('leave-detail').textContent.includes('three game modes'));});
test('expired rooms do not trap a player when returning to game modes',async()=>{const h=await harness();await h.run('create()');h.run("remote=true;code='ABCDEF123456';state.status='finished'");h.ctx.fetch=async()=>({ok:false,json:async()=>({error:'room_expired'})});assert.equal(await h.run('returnToModes()'),true);assert.equal(h.run('state'),null);assert.equal(h.run('step'),'modes');});

test('finished match opens a modal once and closes it on rematch or menu',async()=>{const h=await harness();await h.run('create()');let opens=0;h.get('result').showModal=function(){this.open=true;opens++;};h.run("state.status='finished';state.answer='crane';state.winner=0;render()");assert.equal(h.get('result').open,true);assert.match(h.get('result-detail').textContent,/CRANE/);h.run('render()');assert.equal(opens,1);h.get('review-board').onclick();h.run('render();render()');assert.equal(h.get('result').open,false);assert.equal(opens,1);h.get('view-result').onclick();assert.equal(h.get('result').open,true);assert.equal(opens,2);h.run("state.status='playing';render()");assert.equal(h.get('result').open,false);h.run("state.status='finished';render()");assert.equal(opens,3);await h.run('returnToModes()');assert.equal(h.get('result').open,false);assert.equal(h.run('state'),null);});
