import {test} from 'node:test';import assert from 'node:assert/strict';import worker from '../dist/server/index.js';import {testEnv} from './d1.js';
const players=['a','b','c'].map(x=>x.repeat(64)),ids=['1','2','3'].map(x=>x.repeat(32));
async function request(env,path,p,body){const r=await worker.fetch(new Request('https://game.test/api/'+path,{method:'POST',headers:{authorization:'Bearer '+players[p],'content-type':'application/json',origin:'https://game.test'},body:JSON.stringify({match:1,...body})}),env);return {status:r.status,...await r.json()};}
const search=(e,p,extra={})=>request(e,'matchmaking/search',p,{searchId:ids[p],mode:'duel',lang:'en',name:'Player '+p,...extra});
test('three simultaneous searches create one pair, one waiter and no exposed secret',async()=>{const e=testEnv();await Promise.all([search(e,0),search(e,1),search(e,2)]);const results=await Promise.all([search(e,0),search(e,1),search(e,2)]);const matched=results.filter(x=>x.status==='matched');assert.equal(matched.length,2);assert.equal(results.filter(x=>x.status==='searching').length,1);assert.equal(matched[0].room.code,matched[1].room.code);assert.notEqual(matched[0].room.me,matched[1].room.me);assert.equal(e.sql.prepare('SELECT COUNT(*) n FROM rooms').get().n,1);assert.equal(matched[0].room.answer,null);assert(!JSON.stringify(matched).includes('auth'));assert.equal(matched[0].room.status,'waiting');for(const p of [0,1,2]){const r=results[p];if(r.status==='matched')await request(e,'rooms/'+r.room.code+'/ready',p,{});}const row=JSON.parse(e.sql.prepare('SELECT data FROM rooms').get().data);assert.equal(row.status,'playing');e.sql.close();});
test('duplicate requests never match self and different modes or languages never pair',async()=>{const e=testEnv();await Promise.all([search(e,0),search(e,0),search(e,1,{lang:'pt'}),search(e,2,{mode:'race'})]);assert.equal(e.sql.prepare('SELECT COUNT(*) n FROM rooms').get().n,0);assert.equal(e.sql.prepare('SELECT COUNT(*) n FROM match_queue').get().n,3);e.sql.close();});
test('cancel fences delayed search and old cancellation cannot delete new search',async()=>{const e=testEnv();await request(e,'matchmaking/cancel',0,{searchId:ids[0]});assert.equal((await search(e,0)).status,'cancelled');const fresh='4'.repeat(32);assert.equal((await search(e,0,{searchId:fresh})).status,'searching');await request(e,'matchmaking/cancel',0,{searchId:ids[0]});const ticket=e.sql.prepare('SELECT * FROM match_queue').get();assert.equal(ticket.search_id,fresh);assert.equal(ticket.status,'waiting');e.sql.close();});
test('pair-before-cancel returns assigned room for leave and lost response retries keep same seat',async()=>{const e=testEnv();await search(e,0);const pair=await search(e,1);assert.equal(pair.status,'matched');const cancel=await request(e,'matchmaking/cancel',0,{searchId:ids[0]});assert.equal(cancel.status,'matched');assert.equal(cancel.room.code,pair.room.code);assert.equal((await search(e,1)).room.code,pair.room.code);await request(e,'rooms/'+cancel.room.code+'/leave',0,{});assert.equal((await search(e,1,{searchId:'5'.repeat(32)})).status,'searching');e.sql.close();});
test('stale leases never pair and expired online lobbies terminate',async()=>{const e=testEnv();await search(e,0);e.sql.prepare('UPDATE match_queue SET lease_until=0').run();assert.equal((await search(e,1)).status,'searching');await search(e,0);const row=e.sql.prepare('SELECT code,data FROM rooms').get(),g=JSON.parse(row.data);g.readyUntil=Date.now()-1;e.sql.prepare('UPDATE rooms SET data=? WHERE code=?').run(JSON.stringify(g),row.code);const r=await request(e,'rooms/'+row.code+'/guess',0,{word:'crane'});assert.equal(r.status,'finished');assert.equal(r.reason,'cancelled');e.sql.close();});
test('batch failure rolls back the room and pair assignments',async()=>{const e=testEnv();await search(e,0);e.sql.exec("CREATE TRIGGER fail_pair BEFORE UPDATE ON match_queue WHEN NEW.status='matched' BEGIN SELECT RAISE(ABORT,'test rollback'); END;");const r=await search(e,1);assert.equal(r.status,503);assert.equal(e.sql.prepare('SELECT COUNT(*) n FROM rooms').get().n,0);assert.equal(e.sql.prepare("SELECT COUNT(*) n FROM match_queue WHERE status='matched'").get().n,0);e.sql.close();});
test('each cancelled generation stays retired after newer searches are cancelled',async()=>{const e=testEnv();const newer='9'.repeat(32);await request(e,'matchmaking/cancel',0,{searchId:ids[0]});await search(e,0,{searchId:newer});await request(e,'matchmaking/cancel',0,{searchId:newer});assert.equal((await search(e,0)).status,'cancelled');await search(e,1);assert.equal(e.sql.prepare('SELECT COUNT(*) n FROM rooms').get().n,0);e.sql.close();});
test('completed search retries cannot requeue, fresh search can; heartbeat retains entry time',async()=>{const e=testEnv();await search(e,0);e.sql.prepare('UPDATE match_queue SET created=123').run();await search(e,0);assert.equal(e.sql.prepare('SELECT created FROM match_queue').get().created,123);const pair=await search(e,1);await request(e,'rooms/'+pair.room.code+'/leave',0,{});assert.equal((await search(e,0)).status,'cancelled');assert.equal((await search(e,0,{searchId:'7'.repeat(32)})).status,'searching');e.sql.close();});
test('online uses fixed 30 seconds regardless of submitted timing',async()=>{const e=testEnv();await search(e,0,{seconds:15});const paired=await search(e,1,{seconds:60});assert.equal(paired.status,'matched');assert.equal(paired.room.settings.seconds,30);assert.equal(paired.room.settings.clockMode,'response');assert.equal(paired.room.deadline,0);e.sql.close();});
test('fresh different-mode search declines an unaccepted old rematch',async()=>{const e=testEnv();await search(e,0);const pair=await search(e,1),code=pair.room.code;await request(e,'rooms/'+code+'/ready',0,{});await request(e,'rooms/'+code+'/ready',1,{});const g=JSON.parse(e.sql.prepare('SELECT data FROM rooms WHERE code=?').get(code).data);await request(e,'rooms/'+code+'/guess',0,{word:g.answer});await request(e,'rooms/'+code+'/guess',1,{word:g.answer});await request(e,'rooms/'+code+'/rematch',1,{});const fresh=await search(e,0,{searchId:'8'.repeat(32),mode:'race',seconds:600});assert.equal(fresh.status,'searching');const old=JSON.parse(e.sql.prepare('SELECT data FROM rooms WHERE code=?').get(code).data);assert.equal(old.status,'finished');assert(old.players.some(x=>x.departed));const next=await search(e,2,{mode:'race',seconds:600});assert.equal(next.status,'matched');assert.notEqual(next.room.code,code);assert.equal(next.room.settings.mode,'race');assert.equal(next.room.settings.seconds,30);e.sql.close();});
