import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';import worker from '../dist/server/index.js';
import {testEnv as env} from './d1.js';
const a='a'.repeat(64),b='b'.repeat(64),c='c'.repeat(64);
async function request(e,path,token=a,body){const r=await worker.fetch(new Request('https://game.test'+path,{method:body?'POST':'GET',headers:{authorization:'Bearer '+token,...(body?{'content-type':'application/json',origin:'https://game.test'}:{})},...(body?{body:JSON.stringify({match:1,...body})}:{})}),e);return {status:r.status,data:await r.json()};}
async function room(e,config={}){const r=await request(e,'/api/rooms',a,{name:'A',settings:config});assert.equal(r.status,200);const row=e.sql.prepare('SELECT data FROM rooms WHERE code=?').get(r.data.code);const g=JSON.parse(row.data);g.answer='apple';e.sql.prepare('UPDATE rooms SET data=? WHERE code=?').run(JSON.stringify(g),r.data.code);return r.data.code;}
test('two clients join, ready, submit concurrently and restore without leaking secret',async()=>{const e=env();const code=await room(e,{mode:'duel',seconds:30,sudden:false});assert.equal((await request(e,`/api/rooms/${code}`,b)).status,403);const j=await request(e,`/api/rooms/${code}/join`,b,{name:'B'});assert.equal(j.data.players[1].ready,false);assert.equal((await request(e,`/api/rooms/${code}/join`,c,{name:'C'})).status,409);await request(e,`/api/rooms/${code}/ready`,b,{});const results=await Promise.all([request(e,`/api/rooms/${code}/guess`,a,{word:'crane'}),request(e,`/api/rooms/${code}/guess`,b,{word:'slate'})]);assert(results.every(x=>x.status===200));const current=await request(e,`/api/rooms/${code}`,a);assert.equal(current.data.rows.length,2);assert.equal(current.data.answer,null);assert(!JSON.stringify(current.data).includes('auth'));assert.equal(current.data.revision,4);const again=await request(e,`/api/rooms/${code}`,a);assert.equal(current.data.deadline,again.data.deadline);e.sql.close();});
test('concurrent joins admit one guest only',async()=>{const e=env(),code=await room(e);const result=await Promise.all([request(e,`/api/rooms/${code}/join`,b,{name:'B'}),request(e,`/api/rooms/${code}/join`,c,{name:'C'})]);assert.deepEqual(result.map(r=>r.status).sort(),[200,409]);e.sql.close();});
test('server enforces late timeout and returns selected word only after finish',async()=>{const e=env(),code=await room(e,{mode:'duel',seconds:15,sudden:false});await request(e,`/api/rooms/${code}/join`,b,{name:'B'});await request(e,`/api/rooms/${code}/ready`,b,{});const row=e.sql.prepare('SELECT data FROM rooms WHERE code=?').get(code),g=JSON.parse(row.data);g.deadline=Date.now()-10;const answer=g.answer;e.sql.prepare('UPDATE rooms SET data=? WHERE code=?').run(JSON.stringify(g),code);const r=await request(e,`/api/rooms/${code}/guess`,a,{word:answer});assert.equal(r.data.status,'finished');assert.equal(r.data.winner,null);assert.equal(r.data.reason,'timeout');assert.equal(r.data.answer,answer);e.sql.close();});
test('same player retry join is idempotent and rooms expire',async()=>{const e=env(),code=await room(e);await request(e,`/api/rooms/${code}/join`,b,{name:'B'});assert.equal((await request(e,`/api/rooms/${code}/join`,b,{name:'B'})).status,200);e.sql.prepare('UPDATE rooms SET expires=? WHERE code=?').run(Date.now()-1,code);assert.equal((await request(e,`/api/rooms/${code}`,a)).status,404);e.sql.close();});
test('server preserves response deadline across refresh and rejects late reply',async()=>{const e=env(),code=await room(e,{mode:'duel',clockMode:'response',seconds:30,sudden:false});await request(e,`/api/rooms/${code}/join`,b,{name:'B'});await request(e,`/api/rooms/${code}/ready`,b,{});assert.equal((await request(e,`/api/rooms/${code}`,a)).data.deadline,0);const locked=await request(e,`/api/rooms/${code}/guess`,a,{word:'crane'});const restored=await request(e,`/api/rooms/${code}`,b);assert.equal(restored.data.deadline,locked.data.deadline);assert.equal(restored.data.ownPending,'');assert.equal(restored.data.rows.length,0);const g=JSON.parse(e.sql.prepare('SELECT data FROM rooms WHERE code=?').get(code).data);g.deadline=Date.now()-1;e.sql.prepare('UPDATE rooms SET data=? WHERE code=?').run(JSON.stringify(g),code);const late=await request(e,`/api/rooms/${code}/guess`,b,{word:'apple'});assert.equal(late.data.winner,0);assert.equal(late.data.reason,'timeout');e.sql.close();});
test('delayed requests from an earlier match cannot guess, ready or leave the rematch',async()=>{const e=env(),code=await room(e,{mode:'duel',seconds:0});await request(e,`/api/rooms/${code}/join`,b,{name:'B'});await request(e,`/api/rooms/${code}/ready`,b,{});await request(e,`/api/rooms/${code}/guess`,a,{word:'apple'});await request(e,`/api/rooms/${code}/guess`,b,{word:'crane'});await request(e,`/api/rooms/${code}/rematch`,a,{});await request(e,`/api/rooms/${code}/ready`,b,{match:2});for(const action of ['guess','leave','ready','rematch']){const r=await request(e,`/api/rooms/${code}/${action}`,a,{match:1,word:'apple'});assert.equal(r.status,409);assert.equal(r.data.error,'stale_match');assert.equal(r.data.room.match,2);}const g=(await request(e,`/api/rooms/${code}`,a)).data;assert.equal(g.status,'playing');assert.equal(g.ownPending,'');assert.equal(g.players[0].departed,false);e.sql.close();});
test('leaving a finished room closes rematch participation',async()=>{const e=env(),code=await room(e,{mode:'duel',seconds:0});await request(e,`/api/rooms/${code}/join`,b,{name:'B'});await request(e,`/api/rooms/${code}/ready`,b,{});await request(e,`/api/rooms/${code}/guess`,a,{word:'apple'});await request(e,`/api/rooms/${code}/guess`,b,{word:'crane'});await request(e,`/api/rooms/${code}/leave`,a,{});assert.equal((await request(e,`/api/rooms/${code}/rematch`,b,{})).data.error,'opponent_left');e.sql.close();});
test('revision sync returns current state immediately when the client is behind',async()=>{const e=env(),code=await room(e,{mode:'duel',seconds:0});const synced=await request(e,`/api/rooms/${code}/sync?since=-1`,a);assert.equal(synced.status,200);assert.equal(synced.data.revision,0);assert.equal(synced.data.code,code);e.sql.close();});
test('Word Swap room keeps selections private and scores each assigned word',async()=>{const e=env(),code=await room(e,{mode:'swap',seconds:0});await request(e,`/api/rooms/${code}/join`,b,{name:'B'});await request(e,`/api/rooms/${code}/ready`,b,{});await request(e,`/api/rooms/${code}/guess`,a,{word:'crane'});const hidden=await request(e,`/api/rooms/${code}`,b);assert(!JSON.stringify(hidden.data).includes('crane'));await request(e,`/api/rooms/${code}/guess`,b,{word:'apple'});await request(e,`/api/rooms/${code}/guess`,a,{word:'apple'});const finished=await request(e,`/api/rooms/${code}`,a);assert.equal(finished.data.winner,0);assert.equal(finished.data.answer,'apple');e.sql.close();});
